### ISSUE TITLE
macOS Big Sur 11.0.1 (20B29) > Libusb missing > failed to install libusb

### ISSUE THREAD

**Issue by iComet** [rA9stuff/LeetDown#16]

**Comment by rA9stuff** [comment]
Hi, please run this command on terminal. It will show you the logs generated by leetdown. Then copy and paste the logs here. 
``/Applications/leetdown.app/Contents/MacOS/leetdown.app``

**Comment by jackhu9527** [comment]
Try this:

About abcde : Library for USB device access!
More Information: http://libusb.info
Steps:

Launch Terminal by pressing command+space, type terminal and hit Enter key.
Run
`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null`
Install
`brew install libusb`
Done!

**Comment by rA9stuff** [comment]
@jackhu9527 Yeah it fixes it but I want to know what's wrong with leetdown so I can fix it for good.

**Comment by RolphNL** [comment]
Currently having the same issue, iPad Air - Cellular. Got updated to iOS 12.4.9 but want to downgrade to 10.3.3 for obvious reasons.

Unfortunately LeetDown wants to install "libusb" when I approve it, it fails
- I tried to see run the command on terminal but nothing shows up
- the second command in terminal, it doesn't allow me to continue because: "need sudo access" (while I am administrator)..

**Comment by khoitran18** [comment]
same problem with my iPhone 5s

**Comment by davidmacae** [comment]
Olá, execute este comando no terminal. Ele irá mostrar os logs gerados pelo leetdown. Em seguida, copie e cole os logs aqui.
/Applications/leetdown.app/Contents/MacOS/leetdown.app




its > -bash: /Applications/leetdown.app/Contents/MacOS/leetdown.app: No such file or directory





MacBook-Pro-de-Jota:~ jota$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null

Need sudo access on macOS (e.g. the user jota to be an Administrator)!
MacBook-Pro-de-Jota:~ jota$ sudo ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
Password:
Don't run this as root!
MacBook-Pro-de-Jota:~ jota$

**Comment by DKingPhotographi** [comment]
Still Having LIBUSB Download/install failure, I have tried a number of methods but I am not really good with coding, just been researching and trying codes that others suggest. This is my latest attempts still with no success. Please let me know where else or what else I may try. I am trying to restore 10.3.3 to 1st gen ipad air. Thank you all for your time.

Last login: Thu Jan 14 15:35:32 on console
Admins-MBP:~ DKINGPHOTOGRAPHI$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
Need sudo access on macOS (e.g. the user DKINGPHOTOGRAPHI to be an Administrator)!
Admins-MBP:~ DKINGPHOTOGRAPHI$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
Need sudo access on macOS (e.g. the user DKINGPHOTOGRAPHI to be an Administrator)!
Admins-MBP:~ DKINGPHOTOGRAPHI$ sudo ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
Password:
Don't run this as root!
Admins-MBP:~ DKINGPHOTOGRAPHI$ brew install libusb
Error: You have not agreed to the Xcode license. Please resolve this by running:
  sudo xcodebuild -license accept
Admins-MBP:~ DKINGPHOTOGRAPHI$ sudo xcodebuild -license accept
Admins-MBP:~ DKINGPHOTOGRAPHI$ brew install libusb
Updating Homebrew...
Warning: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

Error: git: no bottle available!
You can try to install from source with:
  brew install --build-from-source git
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
Error: Git must be installed and in your PATH!
Warning: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

Error: libusb: no bottle available!
You can try to install from source with:
  brew install --build-from-source libusb
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
Admins-MBP:~ DKINGPHOTOGRAPHI$ ./configure
-bash: ./configure: No such file or directory
Admins-MBP:~ DKINGPHOTOGRAPHI$ sudo ./configure
Password:
sudo: ./configure: command not found
Admins-MBP:~ DKINGPHOTOGRAPHI$ sudo make
make: *** No targets specified and no makefile found.  Stop.
Admins-MBP:~ DKINGPHOTOGRAPHI$ sudo ./configure make
sudo: ./configure: command not found
Admins-MBP:~ DKINGPHOTOGRAPHI$ sudo make ./configure
make: *** No rule to make target `configure'.  Stop.
Admins-MBP:~ DKINGPHOTOGRAPHI$ .configure LIBUSB_CFLAGS=-I/usr/local/include/libusb-1.0.22.el_capitain.bottle.tar.gz LIBUSB_LIBS="-L/usr/local/lib -lusb-1.0"
-bash: .configure: command not found
Admins-MBP:~ DKINGPHOTOGRAPHI$ sudo make ./configure LIBUSB_CFLAGS=-I/usr/local/include/libusb-1.0.22.el_capitain.bottle.tar.gz LIBUSB_LIBS="-L/usr/local/lib -lusb-1.0"
Password:
make: *** No rule to make target `configure'.  Stop.
Admins-MBP:~ DKINGPHOTOGRAPHI$ /usr/local/lib
-bash: /usr/local/lib: is a directory
Admins-MBP:~ DKINGPHOTOGRAPHI$ show content /usr/local/lib
-bash: show: command not found
Admins-MBP:~ DKINGPHOTOGRAPHI$ /usr/sbin/pcscd--version
-bash: /usr/sbin/pcscd--version: No such file or directory
Admins-MBP:~ DKINGPHOTOGRAPHI$ /usr/sbin/pcscd --version
-bash: /usr/sbin/pcscd: No such file or directory
Admins-MBP:~ DKINGPHOTOGRAPHI$ sudo ./configure
Password:
sudo: ./configure: command not found
Admins-MBP:~ DKINGPHOTOGRAPHI$ sudo make
make: *** No targets specified and no makefile found.  Stop.
Admins-MBP:~ DKINGPHOTOGRAPHI$ sudo make .configure LIBUSB_CFLAGS=-I/usr/admins/downloads/vieux-master/resources/ipwndfu/libusbfinder
Password:
make: *** No rule to make target `.configure'.  Stop.
Admins-MBP:~ DKINGPHOTOGRAPHI$

**Comment by man6130772** [comment]
i solve this promblem with 'brew update'

**Comment by DKingPhotographi** [comment]
I’m interested to know the resolution
